# ==============================================================================
#    NAME: scripts/0_common.R
#   INPUT: None
# ACTIONS: Set common settings used across the scripts
#  OUTPUT: Set of global variables loaded into R's environment
# ==============================================================================

# ==============================================================================
# File locations
# ==============================================================================

f <- list(
  "act" = "data/aircraft.csv", # Aircraft data from Sun et al. (2020)
  "net" = "data/netcdf.csv", # List of NetCDF files from the ESGF
  "geo" = "data/geolocation.csv", # Airport coordinates from OurAirports.com
  "out" = "outfile.log", # Log file for the scripts that require one
  "rwy" = "data/runways.csv", # Runways and TODA from Lufthansa Systems
  "tra" = "data/traffic.csv" # 2019 traffic by airport from IATA
)

# ==============================================================================
# Directory locations
# ==============================================================================

d <- list(
  "cal" = "data/cal", # Calibrated takeoff performance data
  "cli" = "data/cli", # Climate data in NetCDF format
  "plt" = "plots" # Plots generated by R
)

# ==============================================================================
# Database parameters
# ==============================================================================

db <- list(
  "cnf" = ".my.cnf", # File that contains the database connection parameters
  "grp" = "phd", # Group name within the cnf file
  "act" = "act", # Aircraft characteristics for the takeoff simulation
  "cal" = "cal", # Calibration data
  "cli" = "cli", # Climate data post-transformation
  "imp" = "imp", # Climate data imported from the NetCDF files
  "pop" = "pop", # Population and sample airports
  "tko" = "tko" # Takeoff performance calculation outputs
)

# ==============================================================================
# Takeoff simulation parameters
# ==============================================================================

sim <- list(
  # Natural constants
  "g"           = 9.806665, # Gravitational acceleration constant in m/s²
  "gamma"       = 1.401, # Adiabatic index for dry air
  "ps_isa"      = 101325L, # Air pressure in Pa at sea level under ISA
  "Rd"          = 287.058, # Specific gas constant for dry air in J/(kg·K)
  # Runway constants
  "mu"          = .02, # Friction coefficient for dry concrete/asphalt
  "theta"       = 0L, # Runway slope in °
  # Simulation settings
  "flap_angle"  = 10L, # Flap deflection angle in takeoff configuration
  "climb_angle" = 7.7, # Average climb angle to screen height
  "int"         = 10L, # Simulation resolution (integration steps)
  "pop_thr"     = 10^6 # Minimum passenger traffic for airport selection
)

# EOF
