# ==============================================================================
#    NAME: scripts/0_common.R
#   INPUT: None
# ACTIONS: Set common settings used across the scripts
#  OUTPUT: Set of global variables loaded into R's environment
# RUNTIME: N/A
#  AUTHOR: Thomas D. Pellegrin <thomas@pellegr.in>
#    YEAR: 2022
# ==============================================================================

# ==============================================================================
# 0 Directory locations
# ==============================================================================

dir <- list(
  "cal" = "data/cal", # Calibrated takeoff performance data
  "cli" = "data/cli", # Climate data in NetCDF format
  "log" = "logs",     # Log files
  "plt" = "plots",    # Plots generated by R
  "res" = "data/res"  # Results
)

# ==============================================================================
# 1 File locations
# ==============================================================================

fls <- list(
  "act" = "data/act/aircraft.csv",    # Aircraft data from Sun et al. (2020)
  "net" = "data/cli/netcdf.csv",      # List of NetCDF files from the ESGF
  "geo" = "data/pop/geolocation.csv", # Airport coordinates from OurAirports.com
  "rwy" = "data/pop/runways.csv",     # Runways and TODA from Lufthansa Systems
  "tra" = "data/pop/traffic.csv"      # 2019 traffic by airport from IATA
)

# ==============================================================================
# 2 Database parameters
# ==============================================================================

dat <- list(
  "cnf" = ".my.cnf", # File that contains the database connection parameters
  "grp" = "phd",     # Group name within the cnf file
  "act" = "act",     # Aircraft characteristics for the takeoff simulation
  "cal" = "cal",     # Calibration data
  "cli" = "cli",     # Climate data post-transformation
  "imp" = "imp",     # Climate data imported from the NetCDF files
  "pop" = "pop",     # Population and sample airports
  "tko" = "tko",     # Takeoff performance calculation outputs
  "an1" = "an1",     # Climate change summary
  "an2" = "an2",     # Takeoff outcomes summary
  "an3" = "an3",     # Research questions summary
  "idx" = "idx"      # Index name
)

# ==============================================================================
# 3 Aircraft types
# ==============================================================================

act <- list(
  "Airbus A320neo"   = "A20n", # With LEAP-1A29 engines
  "Airbus A350-900"  = "A359", # With Trent XWB-84 engines
  "Boeing 737 MAX 9" = "B39m", # With CFM LEAP-1B27 engines
  "Boeing 787-9"     = "B789"  # With Trent 1000-K2 engines
)

bod <- list(
  "Narrowbody" = c("A20n", "B39m"),
  "Widebody"   = c("A359", "B789")
)

# ==============================================================================
# 4 Takeoff simulation parameters
# ==============================================================================

sim <- list(
  # Calibration settings
  "clb_ang"     = 7.7,         # Average climb angle to screen height
  "flp_ang"     = 10L,         # Takeoff flap deflection angle in degrees
  "max_lof"     = 1.2,         # Ratio from CLmax to CLlof (Roskam, 2018, p 95)
  "opt_rng"     = c(1.6, 2.2), # Range of cL inputs passed to the optimizer
  "opt_tol"     = 10^-3,       # Optimizer tolerance
  "rwy_frc"     = .02,         # Friction coefficient for dry concrete/asphalt
  "rwy_slp"     = 0L,          # Runway slope in °
  "scr_hgt"     = 35L,         # Minimum screen height above terrain
  "thr_rto"     = 0L,          # Thrust reduction used for calibration
  "tod_mul"     = 1.15,        # Regulatory takeoff distance multiplier
  # Model settings
  "int_stp"     = 10L,         # Integration steps (model resolution)
  "lf_belf"     = .67,         # Break-even load factor
  "pax_avg"     = 87L,         # Mean adult pax weight (Filippone, 2012, p. 52)
  "pop_thr"     = 10^6,        # Minimum passenger traffic for airport sample
  "thr_inc"     = 1L,          # Thrust increase at each iteration in % point
  "thr_ini"     = 25L,         # Thrust reduction for simulation in %
  # Natural constants
  "adb_idx"     = 1.4,         # Adiabatic index for dry air at ISA temperature
  "ft_to_m"     = .3048,       # Number of m in one ft
  "g"           = 9.806665,    # Gravitational acceleration constant in m/s²
  "isa_hdw"     = 0L,          # ISA near-surface headwind in m/s
  "isa_hur"     = 0L,          # ISA sea-level relative humidity in %
  "isa_ps"      = 101325L,     # ISA sea-level air pressure in Pa
  "isa_rho"     = 1.225,       # ISA sea-level air density in kg/m³
  "isa_tas"     = 288.15,      # ISA sea-level air temperature in K
  "k_to_c"      = 273.15,      # Number of °K in 0 °C
  "ps_isa"      = 101325L,     # Air pressure in Pa at sea level under ISA
  "sat_ref"     = 6.1078,      # Ref. saturation vapor pressure at 0°C in mbar
  "rsp_air"     = 287.058,     # Specific gas constant for dry air in J/(kg·K)
  "rsp_h2o"     = 461.495      # Spec. gas constant for water vapor in J/(kg·K)
)

# Absolute latitudinal boundaries for the Earth's climate zones
geo <- list(
  "Antarctic"              = c(-90L,     -66.5635),
  "South temperate zone"   = c(-66.5635, -30L),
  "South subtropical zone" = c(-30L,     -23.4365),
  "Tropical zone"          = c(-23.4365,  23.4365),
  "North subtropical zone" = c( 23.4365,  30L),
  "North temperate zone"   = c( 30L,      66.5635),
  "Arctic"                 = c( 66.5635,  90L)
)

# ==============================================================================
# 5 Common functions
# ==============================================================================

# ==============================================================================
# 5.1 Function to distribute a computational task across cores
# crs = number of cores to use in the cluster
# lib = libraries required by each core
# lst = list to be distributed across cores
# fun = function to be applied to each list item
# ==============================================================================

fn_par_lapply <- function(crs, pkg, lst, fun) {

  # Set the log file to the name of the function being passed
  log <- paste(dir$log, "/", substitute(fun), ".log", sep = "")

  # Clear the log file in case it is not empty
  close(file(description = log, open = "w"))

  # Build the cluster of workers
  cl <- parallel::makeCluster(spec = crs, outfile = log)

  # Have each worker load the required packages
  parallel::clusterCall(
    cl  = cl,
    fun = function() {
      suppressMessages(lapply(X = pkg, FUN = require, character.only = TRUE))
    }
  )

  # Pass all global variables to each worker
  parallel::clusterExport(cl = cl, varlist = ls(.GlobalEnv))

  # Distribute the task across the workers
  parallel::parLapply(cl = cl, X = lst, fun = fun)

  # Shut down the workers
  parallel::stopCluster(cl = cl)

}

# ==============================================================================
# 5.2 Function to execute a SQL query and retrieve the results
# statement = the SQL statement to pass to the database
# ==============================================================================

fn_sql_qry <- function(statement) {

  # Connect to the database
  conn <- DBI::dbConnect(
    RMySQL::MySQL(),
    default.file = dat$cnf,
    group = dat$grp
  )

  # Send the query to the database
  res <- DBI::dbSendQuery(conn = conn, statement = statement)

  # Return the results to a data table
  dt_out <- suppressWarnings(
    data.table::setDT(
      DBI::dbFetch(res = res, n = Inf)
    )
  )

  # Release the database resource
  DBI::dbClearResult(res)

  # Disconnect from the database
  DBI::dbDisconnect(conn)

  # Return the data table
  return(dt_out)

}

# EOF
